/*
 * Copyright (C) 2025 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.android.settings.accessibility.notification;

import static com.android.internal.accessibility.common.NotificationConstants.ACTION_SURVEY_NOTIFICATION_SHOWN;
import static com.android.internal.accessibility.common.NotificationConstants.ACTION_SURVEY_NOTIFICATION_DISMISSED;
import static com.android.internal.accessibility.common.NotificationConstants.EXTRA_PAGE_ID;
import static com.android.internal.accessibility.common.NotificationConstants.EXTRA_SOURCE;
import static com.android.internal.accessibility.common.NotificationConstants.SOURCE_START_SURVEY;

import android.app.Notification;
import android.app.NotificationChannel;
import android.app.NotificationManager;
import android.app.PendingIntent;
import android.app.settings.SettingsEnums;
import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.Intent;
import android.provider.Settings;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

import com.android.server.accessibility.Flags;
import com.android.settings.R;

/**
 * Service to display survey notifications.
 */
public class SurveyNotificationReceiver extends BroadcastReceiver {

    public static final String NOTIFICATION_CHANNEL_ID =
            "com.android.settings.accessibility.notification.SurveyNotificationService";

    // The base ID for notifications is derived from the bug component ID.
    // Page-specific notification IDs are generated by adding the respective pageId to this base.
    private static final int NOTIFICATION_ID_BASE = 751131;
    private static final int START_SURVEY_REQUEST_CODE = 1;

    @Override
    public void onReceive(@NonNull Context context, @NonNull Intent intent) {
        if (!Flags.enableLowVisionHats()) {
            return;
        }

        final NotificationManager notificationManager =
                context.getSystemService(NotificationManager.class);
        if (notificationManager == null) {
            return;
        }

        int pageId = intent.getIntExtra(EXTRA_PAGE_ID, SettingsEnums.PAGE_UNKNOWN);
        int notificationId = getNotificationId(pageId);
        if (ACTION_SURVEY_NOTIFICATION_SHOWN.equals(intent.getAction())) {
            // create a notification channel to post persistent notification
            final NotificationChannel channel =
                    new NotificationChannel(
                            NOTIFICATION_CHANNEL_ID,
                            context.getString(
                                    R.string.accessibility_send_survey_notification_channel),
                            NotificationManager.IMPORTANCE_LOW);
            notificationManager.createNotificationChannel(channel);
            final Notification notification = createNotification(context, pageId);
            if (notification != null) {
                notificationManager.notify(notificationId, notification);
            }
        } else if (ACTION_SURVEY_NOTIFICATION_DISMISSED.equals(intent.getAction())) {
            notificationManager.cancel(notificationId);
        }
    }

    @Nullable
    private Notification createNotification(Context context, int pageId) {
        if (pageId == SettingsEnums.DARK_UI_SETTINGS) {
            return buildNotification(
                    context,
                    context.getString(R.string.dark_theme_survey_notification_title),
                    context.getString(R.string.dark_theme_survey_notification_summary),
                    context.getString(R.string.dark_theme_survey_notification_action),
                    new Intent(Settings.ACTION_DARK_THEME_SETTINGS).setPackage(
                            context.getPackageName()));
        }
        return null;
    }

    private Notification buildNotification(Context context, String title, String text,
            String actionText, Intent notifyIntent) {
        final PendingIntent notifyPendingIntent = createNotifyPendingIntent(context, notifyIntent);
        final Notification.Action action = createAction(notifyPendingIntent, actionText);
        return createNotificationBuilder(context, title, text,
                notifyPendingIntent, action).build();
    }

    private PendingIntent createNotifyPendingIntent(Context context, Intent notifyIntent) {
        notifyIntent.putExtra(EXTRA_SOURCE, SOURCE_START_SURVEY);
        notifyIntent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK
                | Intent.FLAG_ACTIVITY_CLEAR_TOP
                | Intent.FLAG_ACTIVITY_SINGLE_TOP);
        return PendingIntent.getActivity(
                context,
                START_SURVEY_REQUEST_CODE,
                notifyIntent,
                PendingIntent.FLAG_UPDATE_CURRENT | PendingIntent.FLAG_IMMUTABLE);
    }

    private Notification.Action createAction(PendingIntent rateUsPendingIntent,
            String actionText) {
        return new Notification.Action.Builder(
                /* icon= */ null,
                actionText,
                rateUsPendingIntent)
                .build();
    }

    private Notification.Builder createNotificationBuilder(Context context, String title,
            String text, PendingIntent notifyPendingIntent, Notification.Action action) {
        return new Notification.Builder(context, NOTIFICATION_CHANNEL_ID)
                .setContentTitle(title)
                .setContentText(text)
                .setSmallIcon(R.drawable.ic_settings_24dp)
                .setContentIntent(notifyPendingIntent)
                .addAction(action)
                .setFlag(Notification.FLAG_NO_CLEAR, true)
                .setAutoCancel(true);
    }

    /**
     * Generates a notification ID based on a base ID and a page ID. This ensures that notifications
     * for different pages will have distinct IDs.
     *
     * @param pageId The unique identifier of the page for which to generate a notification ID.
     * @return A unique integer representing the notification ID for the given page.
     */
    public static int getNotificationId(int pageId) {
        return NOTIFICATION_ID_BASE + pageId;
    }
}
