/*
 * Copyright (C) 2025 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.android.settings.accessibility.notification;

import static com.android.settings.accessibility.notification.NotificationConstants.EXTRA_DISMISS_NOTIFICATION;
import static com.android.settings.accessibility.notification.NotificationConstants.EXTRA_PAGE_ID;
import static com.android.settings.accessibility.notification.NotificationConstants.EXTRA_SOURCE;
import static com.android.settings.accessibility.notification.NotificationConstants.SOURCE_START_SURVEY;

import android.app.Notification;
import android.app.NotificationChannel;
import android.app.NotificationManager;
import android.app.PendingIntent;
import android.app.Service;
import android.app.settings.SettingsEnums;
import android.content.Intent;
import android.os.IBinder;
import android.provider.Settings;

import androidx.annotation.Nullable;

import com.android.settings.R;

/**
 * Service to display survey notifications.
 */
public class SurveyNotificationService extends Service {

    public static final String NOTIFICATION_CHANNEL_ID =
            "com.android.settings.accessibility.notification.SurveyNotificationService";

    // The base ID for notifications is derived from the bug component ID.
    // Page-specific notification IDs are generated by adding the respective pageId to this base.
    private static final int NOTIFICATION_ID_BASE = 751131;
    private static final int START_SURVEY_REQUEST_CODE = 1;
    private NotificationManager mNotificationManager;

    @Override
    public void onCreate() {
        super.onCreate();
        createNotificationChannel();
    }

    @Override
    public int onStartCommand(@Nullable Intent intent, int flags, int startId) {
        if (intent == null) {
            return START_NOT_STICKY;
        }

        if (mNotificationManager == null) {
            return START_NOT_STICKY;
        }

        int pageId = intent.getIntExtra(EXTRA_PAGE_ID, SettingsEnums.PAGE_UNKNOWN);
        if (pageId == SettingsEnums.PAGE_UNKNOWN) {
            return START_NOT_STICKY;
        }

        int notificationId = getNotificationId(pageId);
        boolean shouldDismiss = intent.getBooleanExtra(EXTRA_DISMISS_NOTIFICATION, false);
        if (shouldDismiss) {
            mNotificationManager.cancel(notificationId);
            return START_NOT_STICKY;
        }

        final Notification notification = createNotification(pageId);
        if (notification != null) {
            mNotificationManager.notify(notificationId, notification);
            return START_NOT_STICKY;
        }

        return START_NOT_STICKY;
    }

    @Nullable
    @Override
    public IBinder onBind(@Nullable Intent intent) {
        return null;
    }

    // create a notification channel to post persistent notification
    private void createNotificationChannel() {
        final NotificationChannel channel =
                new NotificationChannel(
                        NOTIFICATION_CHANNEL_ID,
                        getString(R.string.accessibility_send_survey_notification_channel),
                        NotificationManager.IMPORTANCE_LOW);
        mNotificationManager = getSystemService(NotificationManager.class);
        if (mNotificationManager != null) {
            mNotificationManager.createNotificationChannel(channel);
        }
    }

    @Nullable
    private Notification createNotification(int pageId) {
        if (pageId == SettingsEnums.DARK_UI_SETTINGS) {
            return buildNotification(
                    getString(R.string.dark_theme_survey_notification_title),
                    getString(R.string.dark_theme_survey_notification_summary),
                    getString(R.string.dark_theme_survey_notification_action),
                    new Intent(Settings.ACTION_DARK_THEME_SETTINGS).setPackage(getPackageName()));
        }
        return null;
    }

    private Notification buildNotification(String title, String text, String actionText,
            Intent notifyIntent) {
        final PendingIntent notifyPendingIntent = createNotifyPendingIntent(notifyIntent);
        final Notification.Action action = createAction(notifyPendingIntent, actionText);
        final Notification.Builder builder = createNotificationBuilder(title, text,
                notifyPendingIntent, action);
        return builder.build();
    }

    private PendingIntent createNotifyPendingIntent(Intent notifyIntent) {
        notifyIntent.putExtra(EXTRA_SOURCE, SOURCE_START_SURVEY);
        notifyIntent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK
                | Intent.FLAG_ACTIVITY_CLEAR_TOP
                | Intent.FLAG_ACTIVITY_SINGLE_TOP);
        return PendingIntent.getActivity(
                this,
                START_SURVEY_REQUEST_CODE,
                notifyIntent,
                PendingIntent.FLAG_UPDATE_CURRENT | PendingIntent.FLAG_IMMUTABLE);
    }

    private Notification.Action createAction(PendingIntent rateUsPendingIntent,
            String actionText) {
        return new Notification.Action.Builder(
                /* icon= */ null,
                actionText,
                rateUsPendingIntent)
                .build();
    }

    private Notification.Builder createNotificationBuilder(String title, String text,
            PendingIntent notifyPendingIntent, Notification.Action action) {
        return new Notification.Builder(this, NOTIFICATION_CHANNEL_ID)
                .setContentTitle(title)
                .setContentText(text)
                .setSmallIcon(R.drawable.ic_settings_24dp)
                .setContentIntent(notifyPendingIntent)
                .addAction(action)
                .setFlag(Notification.FLAG_NO_CLEAR, true)
                .setAutoCancel(true);
    }

    /**
     * Generates a notification ID based on a base ID and a page ID. This ensures that notifications
     * for different pages will have distinct IDs.
     *
     * @param pageId The unique identifier of the page for which to generate a notification ID.
     * @return A unique integer representing the notification ID for the given page.
     */
    public static int getNotificationId(int pageId) {
        return NOTIFICATION_ID_BASE + pageId;
    }
}
