/*
 * Copyright 2025 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.android.settings.appfunctions.providers

import androidx.annotation.Keep
import com.android.settings.appfunctions.DeviceStateCategory
import com.google.android.appfunctions.schema.common.v1.devicestate.PerScreenDeviceStates

/**
 * Represents the self-contained result from a single [DeviceStateProvider].
 * This is an immutable data class.
 *
 * @property states The list of [PerScreenDeviceStates] generated by the provider.
 * @property hintText An optional, non-parseable hint text contribution. Null if none.
 */
@Keep
data class DeviceStateProviderResult(
    val states: List<PerScreenDeviceStates>,
    val hintText: String? = null
)

/**
 * Defines the contract for any class that provides device state information.
 *
 * Implementations are responsible for fetching data from a single, well-defined source,
 * such as the Catalyst graph, Android system settings, or a specific OEM API.
 * These providers are designed to be stateless and fully testable in isolation.
 */
@Keep
interface DeviceStateProvider {
    /**
     * Asynchronously gathers device state information.
     *
     * @param requestCategory The category of information requested by the caller. The provider
     * should only add data if it matches the requested category.
     * @return A [DeviceStateProviderResult] containing the device state information.
     */
    suspend fun provide(requestCategory: DeviceStateCategory): DeviceStateProviderResult
}