/*
 * Copyright 2025 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.android.settings.appfunctions

import android.app.appsearch.GenericDocument
import android.util.Log
import androidx.annotation.Keep
import com.android.settings.appfunctions.executors.DeviceStateExecutor
import com.android.settings.appfunctions.executors.DeviceStateExecutorResult
import com.google.android.appfunctions.schema.common.v1.devicestate.DeviceStateMetadataResponse
import com.google.android.appfunctions.schema.common.v1.devicestate.DeviceStateResponse
import com.google.android.appfunctions.schema.common.v1.devicestate.ItemizationType
import com.google.android.appfunctions.schema.common.v1.devicestate.PerScreenMetadata
import kotlinx.coroutines.async
import kotlinx.coroutines.supervisorScope

/**
 * Orchestrates the collection and transformation of device state metadata information.
 *
 * This class executes from multiple [DeviceStateExecutor]s in parallel, aggregates the results to
 * produce the final [DeviceStateMetadataResponse].
 *
 * @property executors The list of [DeviceStateExecutor]s to query for device state metadata.
 */
@Keep
class DeviceStateMetadataProviderAggregator(private val executors: List<DeviceStateExecutor>) :
    DeviceStateAggregator(executors) {
    /**
     * Aggregates device state from all registered providers.
     *
     * This function performs the following steps:
     * 1. Calls all [DeviceStateExecutor]s concurrently to gather device state information.
     * 2. Combines the states and hint text from all provider results.
     * 3. Constructs and returns the final [DeviceStateResponse].
     *
     * @param appFunctionType The device state app function to fetch, passed to each provider.
     * @param deviceLocale The current locale of the device, included in the final response.
     * @return A [DeviceStateResponse] containing the fully aggregated device state.
     */
    override suspend fun aggregate(
        appFunctionType: DeviceStateAppFunctionType,
        params: GenericDocument,
        deviceLocale: String,
    ): DeviceStateMetadataResponse {
        val executorResults = supervisorScope {
            executors
                .map { executor ->
                    async {
                        executor.execute(appFunctionType)
                            as DeviceStateMetadataProviderExecutorResult
                    }
                }
                .mapNotNull {
                    try {
                        it.await()
                    } catch (e: Exception) {
                        Log.e(TAG, "Failed to execute provider", e)
                        null
                    }
                }
        }

        val allHintText = executorResults.mapNotNull { it.hintText }.joinToString(separator = "\n")

        val allStates = mutableListOf<PerScreenMetadata>()
        val allItemizationTypes = mutableMapOf<String, ItemizationType>()

        for (result in executorResults) {
            try {
                allStates.addAll(result.metadata)
            } catch (e: Exception) {
                Log.e(TAG, "Failed to aggregate metadata from an executor", e)
            }

            try {
                result.itemizationTypes.forEach { allItemizationTypes[it.key] = it }
            } catch (e: Exception) {
                Log.e(TAG, "Failed to aggregate itemizationTypes from an executor", e)
            }
        }

        val distinctItemizationTypes = allItemizationTypes.values.toSet()

        return DeviceStateMetadataResponse(
            perScreenMetadata = allStates,
            deviceLocale = deviceLocale,
            itemizationTypes = distinctItemizationTypes.toList(),
            globalHintText = allHintText
        )
    }

    companion object {
        private const val TAG = "DeviceStateMetadataProviderAggregator"
    }
}

/**
 * Represents the self-contained result from a single [DeviceStateExecutor]. This is an immutable
 * data class.
 *
 * @property metadata The list of [PerScreenMetadata] generated by the provider.
 * @property hintText An optional, non-parseable hint text contribution. Null if none.
 * @property itemizationTypes A set of [ItemizationType]s used in the response.
 */
@Keep
data class DeviceStateMetadataProviderExecutorResult(
    val metadata: List<PerScreenMetadata>,
    val hintText: String? = null,
    val itemizationTypes: Set<ItemizationType> = emptySet(),
) : DeviceStateExecutorResult()
